# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeandcomment',
            name='cid',
        ),
    ]
