# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_delete_likeandcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Post')),
            ],
        ),
    ]
