# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='postid',
            new_name='post',
        ),
    ]
