# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20170728_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
