# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
