# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
