# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
