# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20170821_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dp',
            field=models.ImageField(default='C:/Projects/blogproject/myblog/static/profilepic/default/default_dp.png', upload_to=''),
        ),
    ]
