# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_comments_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dp',
            field=models.CharField(default='C:/Projects/blogproject/myblog/static/profilepic/default/default_dp.png', max_length=1000),
        ),
    ]
