# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_auto_20170825_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.FileField(default='profilepic/default/default_dp.png', upload_to=''),
        ),
    ]
