# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_auto_20170828_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dp',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
