# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_auto_20170828_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='dp',
        ),
        migrations.AddField(
            model_name='comments',
            name='authorprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myblog.Profile'),
            preserve_default=False,
        ),
    ]
