# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0024_auto_20170829_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='C:\\Projects\\blogproject\\myblog/media//postsimages/'),
        ),
    ]
